### ISSUE TITLE
Design Language Pages (Due: 10/5)

### ISSUE THREAD

**Issue by benjore** [unfoldingWord-dev/design#1]
Web Team - #27 https://github.com/unfoldingWord-dev/door43.org/issues/27

**Comment by Thajny** [comment]
![language dashboard 2](https://cloud.githubusercontent.com/assets/21183377/19940575/23ce995e-a0fb-11e6-82d7-fcee760c6094.jpg)
![language dashboard](https://cloud.githubusercontent.com/assets/21183377/19940576/23d9298c-a0fb-11e6-88a0-7e8eb306b691.jpg)
