### ISSUE TITLE
Design Bible Navigation

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/design#11]
We need a screen for https://github.com/unfoldingWord-dev/door43.org/issues/190.

**Comment by Thajny** [comment]
https://live.door43.org/u/richmahn/en-obs/469fe69724/

**Comment by Thajny** [comment]
![bible nav 1](https://cloud.githubusercontent.com/assets/21183377/19940003/3504b3a4-a0f9-11e6-9209-f1631c816880.jpg)
![bible nav 2](https://cloud.githubusercontent.com/assets/21183377/19940004/3506128a-a0f9-11e6-9919-8c76da11b6c5.jpg)
