### ISSUE TITLE
Door43 License links

### ISSUE THREAD

**Issue by benjore** [unfoldingWord-dev/design#113]
- [x] Make all links in the Door43 license available (offline) in a pop-up
- [x] Include a hyperlink to the actual information source

**Comment by Thajny** [comment]
![new-terms 2](https://cloud.githubusercontent.com/assets/21183377/24675963/c550efb6-1946-11e7-8d05-6cf01bc1c5ad.png)
![new-terms-1](https://cloud.githubusercontent.com/assets/21183377/24675962/c550d850-1946-11e7-9935-6f814027caa2.png)
