### ISSUE TITLE
tC Style Sheet - Cards

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/design#125]

**Comment by benjore** [comment]
- [ ] Actionable Modal
  - [ ] example: Skip warning (might be unique)
- [x] Alert Modal
  - [x] example: trying to log in with no username
- [x] Regular cards being used in the main screen
  - [x] example: scripture pane, check info card, etc.

**Comment by Thajny** [comment]
![modals 1](https://cloud.githubusercontent.com/assets/21183377/26318802/01313412-3ee2-11e7-9bf9-7f89e6ae3f40.png)
![modals](https://cloud.githubusercontent.com/assets/21183377/26318801/012bcb6c-3ee2-11e7-9cc6-70417d4cc344.png)
