### ISSUE TITLE
Sprint #24 Review Follow-up

### ISSUE THREAD

**Issue by benjore** [unfoldingWord-dev/design#126]
- [x] tC Buttons
  - [x] Keep the Secondary Button that doesn't animate
- [x] tC Colors
  - [x] Keep the Dark Blue
- [x] tC walk-through
  - [x] Remove Disabled actions (that is, actions that are not available in this release)
    - [x] EXCEPTION: `Import Local Project` - Keep this, create a pop-over (on hover) with the verbiage explaining that it is coming soon. 
    - [x] EXCEPTION: `Create Door43 Account` - use modal you already designed
  - [x] Add Wifi icon to: 
    - [x] "Log In" button
  - [x] Create new walk-thru with all the above changes
  - [x] Update the tC GitBoard

**Comment by Thajny** [comment]
https://xd.adobe.com/view/105373ea-fd68-4cf5-8f07-61a3b67d4850/
