### ISSUE TITLE
Mockup Reply to Comment Feature

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/design#129]

**Comment by Thajny** [comment]
![obs 2](https://cloud.githubusercontent.com/assets/21183377/25456461/902e33ee-2a98-11e7-815c-852c32741e42.png)
![obs 3](https://cloud.githubusercontent.com/assets/21183377/25456462/902f54ae-2a98-11e7-81f5-146c663c2047.png)
![obs 4](https://cloud.githubusercontent.com/assets/21183377/25456460/902d9a92-2a98-11e7-81bb-a37089f7f877.png)
