### ISSUE TITLE
Design OBS Navigation

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/design#13]
We need a screen for https://github.com/unfoldingWord-dev/door43.org/issues/189.

**Comment by Thajny** [comment]
![obs issue 1](https://cloud.githubusercontent.com/assets/21183377/19938091/bcf37a28-a0f1-11e6-9cb2-3829e0f195cb.jpg)
![obs issue 2](https://cloud.githubusercontent.com/assets/21183377/19938093/bd05bee0-a0f1-11e6-82e8-33c3e5d69521.jpg)

**Comment by Thajny** [comment]
![obs nav 1](https://cloud.githubusercontent.com/assets/21183377/19940213/dcd09508-a0f9-11e6-8518-e37004848758.jpg)
![obs nav 2](https://cloud.githubusercontent.com/assets/21183377/19940214/dcd7e1a0-a0f9-11e6-9b5c-d6adb28dc7ca.jpg)
