### ISSUE TITLE
Learn about OBS

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/design#135]
Learn about OBS by visiting, reading, watching the following:

- https://unfoldingword.org/stories/
- https://live.door43.org/u/Door43/en-obs/b4f4d698df/
- https://unfoldingword.org/en/?resource=open-bible-stories
- https://www.youtube.com/channel/UC5wJwYUEOdaiT2DGGgepSjg
- Download unfoldingWord Android app and check out OBS on it ;)

Start doing a "translation" of OBS in translationStudio, upload your work, view it on Door43.

Take notes throughout the process on the good, the bad, and the ugly.

**Comment by Thajny** [comment]
https://docs.google.com/document/d/1QBDsFxM56xcy8w7Qkc1j2lkJ4EnZsqztK6AeKbRmifs/edit
