### ISSUE TITLE
Changing/Adding verses in tC verse check

### ISSUE THREAD

**Issue by benjore** [unfoldingWord-dev/design#140]
# Story
As a *checker whose translation's versification is slightly messed up* I want to *be able to change or add the verses that are being checked* so that *the messed up versification in my translation does not preclude me from completing the check*.

**Comment by Thajny** [comment]
![verse add-subtract](https://cloud.githubusercontent.com/assets/21183377/25539582/7a683ebc-2c0d-11e7-9977-e121e9931dc0.png)
