### ISSUE TITLE
Dynamic navigation buttons

### ISSUE THREAD

**Issue by benjore** [unfoldingWord-dev/design#142]
See details in https://github.com/unfoldingWord-dev/translationCore/issues/1182

**Comment by benjore** [comment]
- [x] Change the button from "Skip" to "Next"
- [x] Change the button from "Save & Continue" to "Save & Next"
- [x] Add a dialog box when "Next" is clicked telling the user to make a highlight
  - [x] Add a checkbox for "Do not show this warning again"

**Comment by Thajny** [comment]
![tranlsationwords full scrip 31](https://cloud.githubusercontent.com/assets/21183377/25539591/88c71b54-2c0d-11e7-9ec4-e0a0475063a2.png)
