### ISSUE TITLE
Define rules for capitalization in tC - headers, instructions, etc.

### ISSUE THREAD

**Issue by benjore** [unfoldingWord-dev/design#143]

**Comment by Thajny** [comment]
![fonts](https://cloud.githubusercontent.com/assets/21183377/25539603/99541058-2c0d-11e7-926e-7e5cd25a0363.png)

**Comment by Thajny** [comment]
http://blog.apastyle.org/apastyle/2012/03/title-case-and-sentence-case-capitalization-in-apa-style.html
For reference if it is unclear what title case and sentence case are.
