### ISSUE TITLE
Indicate in check if there has been an edit, comment, or bookmark

### ISSUE THREAD

**Issue by benjore** [unfoldingWord-dev/design#145]
As a user, I want to be able to tell at a glance if a verse has a comment, an edit, or a bookmark so that I don't have to waste time exploring to find out for myself. 

- [x] Add status icons next to the current bookmark icon when an edit has been made, or when there is a comment
- [x] change the means of adding a bookmark to a button that says "Add bookmark" and then when there is a bookmark the button changes to say "Remove bookmark"
- [x] Side menu icon placement/procedure should stay the same

**Comment by benjore** [comment]
https://github.com/unfoldingWord-dev/translationCore/issues/1194

**Comment by Thajny** [comment]
![select card 1](https://cloud.githubusercontent.com/assets/21183377/26130446/5c22020c-3a5a-11e7-9d80-bac27eee10ec.png)

**Comment by Thajny** [comment]
![select card 1](https://cloud.githubusercontent.com/assets/21183377/26318620/6209be9a-3ee1-11e7-8c32-f0ddd742cb89.png)
