### ISSUE TITLE
Followup - comments for Door43

### ISSUE THREAD

**Issue by benjore** [unfoldingWord-dev/design#148]
- [x] Clicking "Sign in” - should be a modal in the middle, not a pop-down from the top.
- [x] change unfoldingWord logos to Door43 logos
- [x] Truncate replies (?) and/or Make replies collapsable/expandable

add screens for all the comment stuff to the commenting issue: https://github.com/unfoldingWord-dev/door43.org/issues/22

**Comment by Thajny** [comment]
![obs 2](https://cloud.githubusercontent.com/assets/21183377/26314399/77d07dc6-3ed3-11e7-9759-3316211498ec.png)
![obs 3](https://cloud.githubusercontent.com/assets/21183377/26314398/77cb413a-3ed3-11e7-954f-7b7799aba85a.png)
![obs 4](https://cloud.githubusercontent.com/assets/21183377/26314400/77dc1758-3ed3-11e7-83a8-684214348df7.png)
![obs 5](https://cloud.githubusercontent.com/assets/21183377/26314401/77e9c1be-3ed3-11e7-86e6-b75516ed9cf8.png)
![obs sign in](https://cloud.githubusercontent.com/assets/21183377/26314402/77f72dae-3ed3-11e7-882b-3e97d435dcec.png)
