### ISSUE TITLE
Follow-up: tC dynamic buttons/instructions

### ISSUE THREAD

**Issue by benjore** [unfoldingWord-dev/design#149]
- [x] pop-up when clicking Next without highlighting
  - [x] Skip button = primary 
  - [x] Remove the "Close" next to the "x"
  - [x] Change verbiage “You have not highlighted the correct translation for [line break] [check] [line break] Are you sure you want to skip this check and return to it later?” 
  - [x] Add a Cancel button (secondary)

**Comment by Thajny** [comment]
![popup instrucions](https://cloud.githubusercontent.com/assets/21183377/25625825/323ba5fc-2f23-11e7-9b01-884929e8ee76.png)
