### ISSUE TITLE
Follow-up: For select card

### ISSUE THREAD

**Issue by benjore** [unfoldingWord-dev/design#151]
- [x] Move the expand icon from "My Language" to the blue "Select" bar
- [x] When the expand icon is clicked - the whole "Select" card expands, without the Edit & Comment buttons
  - [x] All verses for that chapter are displayed
  - [x] The chapter/verse is not highlightable
  - [x] If the user scrolls to the top or bottom of the chapter, another chapter loads (maybe add a "Show more" button on the top/bottom?)
  - [x] Allow for highlighting of multiple verses
  - [x] Add "Save Changes" & "Cancel" buttons

**Comment by Thajny** [comment]
![tranlsationwords full scrip 27](https://cloud.githubusercontent.com/assets/21183377/25675704/12b72796-3005-11e7-80b5-c6cc8d0892e1.png)
![tranlsationwords full scrip 30](https://cloud.githubusercontent.com/assets/21183377/25675705/12bb44de-3005-11e7-9ebf-8a3b38a83e8f.png)
![tranlsationwords full scrip 31](https://cloud.githubusercontent.com/assets/21183377/25675703/12b45a52-3005-11e7-9789-36fed4bb8d42.png)
