### ISSUE TITLE
SPIKE: research revision history implementations

### ISSUE THREAD

**Issue by benjore** [unfoldingWord-dev/design#153]
- [ ] GitHub
- [ ] Wikipedia
- [ ] DokuWiki
- [ ] Gogs

**Comment by Thajny** [comment]
Many of the results I found use a system of red and green highlights and are often lacking of a clear format or hiearchy. To non-advanced users, this may come across as overwhelming. One of the best results I found was Dropbox and their version history.

Given how complicated this feature is, it should not be placed in a modal but be put into the normal interface.

A few ideas for implementation:
- By default revisions should be ordered by date and done on a verse by verse basis.
- When synced with other users, they can be segmented by author, in addition to lumping it all together
- Being able to compare different revisions might be helpful (but maybe not a light feature)
- Two different implementations: A light and basic version and a more complicated one.
- Changes between revisions will always be compared to the one previous.
