### ISSUE TITLE
tC Import Project Checks

### ISSUE THREAD

**Issue by benjore** [unfoldingWord-dev/design#154]
## User Story
As a user, I want tC to check and convert my files to the right format so that I don't have to load it into tS and then export it before I can reimport it back into tC. 

## Details
- [ ] When a user Selects a file to import into tC, tC should automatically run a series of checks. If the check passes, the next step should be immediately started. If the check fails/is unknown, the user needs to be prompted to complete the check manually with the option to "Cancel the Import" or fix the problem (if possible) and "Save and Continue"
- [ ] License Check - Projects that have come from tS or are in the resource container format will have this information available. If it is a USFM import, then it likely will have to be entered manually.
- [ ] Completeness check 
  - [ ] Missing Verses and/or chapters - For this iteration, they will not be able to fix the problem here, but they will be able to "Cancel the Import" (and presumably go and fix the problem and try again) or continue with missing data (give them a warning that some tC functionality will be missing... etc. etc.)
  - [ ] Merge conflicts - Users will not be able to resolve the problem here. But they should be warned that continuing will limit functionality etc. etc.
  - [ ] chunks not marked as complete - They should be given the option to mark all chunks as complete
- [ ] USFM formatting check
- [ ] Resource Container Check/Conversion to Resource Container - If the project comes from tS, all of this will import automatically
  - [ ] Language name & tag - This is linked to td.unfoldingword.org and the massive list of names/tags found there.
  - [ ] LTR/RTL
  - [ ] Book Name
  - [ ] Contributors 
  - [ ] Source identifier
  - [ ] Source language 
  - [ ] Source version 
  - [ ] Checking Entity
- [ ] Review - The user should be allowed to see all the information and edit it as necessary. At this point the user should be prompted to "Finish Import"

**Comment by benjore** [comment]
http://resource-container.readthedocs.io/en/latest/structure.html

**Comment by benjore** [comment]
https://git.door43.org/Door43-Catalog/en-ulb/raw/master/manifest.yaml

**Comment by benjore** [comment]
http://resource-container.readthedocs.io/en/latest/manifest.html - This is the project manifest that each book will need.

**Comment by Thajny** [comment]
The interactive prototype can be found here:
https://xd.adobe.com/view/6509deb3-015c-4926-829d-dcefea2a0624/

**Comment by Thajny** [comment]
![preflight check 1](https://cloud.githubusercontent.com/assets/21183377/26076802/98c1073e-397f-11e7-9ea4-314b9447f379.png)
![preflight check 3](https://cloud.githubusercontent.com/assets/21183377/26076807/98ceef16-397f-11e7-9b5e-df15e0167f9f.png)
![preflight check 4](https://cloud.githubusercontent.com/assets/21183377/26076803/98c347b0-397f-11e7-8b3c-41aca6c1fccb.png)
![preflight check 7](https://cloud.githubusercontent.com/assets/21183377/26076806/98c9452a-397f-11e7-835e-fed5645c01c1.png)
![preflight check 5](https://cloud.githubusercontent.com/assets/21183377/26076804/98c4f1c8-397f-11e7-89a4-422095a2a911.png)
![preflight check 8](https://cloud.githubusercontent.com/assets/21183377/26076805/98c55a78-397f-11e7-9137-f4fff8b62d98.png)
![preflight check 6](https://cloud.githubusercontent.com/assets/21183377/26076809/98eeea00-397f-11e7-8ef4-3b67db43edb4.png)
![preflight check 2](https://cloud.githubusercontent.com/assets/21183377/26076808/98da7cf0-397f-11e7-8106-eb19ac10d1a6.png)
