### ISSUE TITLE
tC Dropdown Menus

### ISSUE THREAD

**Issue by benjore** [unfoldingWord-dev/design#157]
- [x] "Home" - should take you to the home screen (No dropdown menu)
- [x] "User" - should have the following
  - [x] "Sign out..."
  - [x] "Leave feedback..."
- [x] "Project"
  - [x] "Upload to Door43..."
  - [x] "Export (CSV)"
  - [x] "Import Online Project..."
  - [x] Recent Projects
- [x] Tools
  - [x] Change tool...

**Comment by Thajny** [comment]
![home](https://cloud.githubusercontent.com/assets/21183377/26319115/542bad72-3ee3-11e7-9936-6e69d4bde99e.png)
![project dropdown 1](https://cloud.githubusercontent.com/assets/21183377/26319114/542b68bc-3ee3-11e7-81e5-1b1584d75446.png)
![project dropdown 3](https://cloud.githubusercontent.com/assets/21183377/26319116/542c8c9c-3ee3-11e7-9c48-7c4f003a31d2.png)
![project dropdown 5](https://cloud.githubusercontent.com/assets/21183377/26319118/542e3fd8-3ee3-11e7-952f-0b4a8a1feb17.png)
![project dropdown 4](https://cloud.githubusercontent.com/assets/21183377/26319117/542d7a4e-3ee3-11e7-8d04-5800940151f4.png)
![project dropdown](https://cloud.githubusercontent.com/assets/21183377/26319119/5430ed64-3ee3-11e7-864d-575e8cc3167a.png)
![tool dropdown](https://cloud.githubusercontent.com/assets/21183377/26319120/543daa2c-3ee3-11e7-963d-48d3532c7d80.png)
![user dropdown](https://cloud.githubusercontent.com/assets/21183377/26319121/543eec5c-3ee3-11e7-993b-1496c6f5fcec.png)
