### ISSUE TITLE
Sorting the Side Menu

### ISSUE THREAD

**Issue by benjore** [unfoldingWord-dev/design#159]
## User Story

As a user, I want to be able to sort the side menu so that I can easily find what I am looking for. 

## Specs
- [x] The user needs to be able to filtered by
  - [x] Bookmark
  - [x] Edits
  - [x] Comments
  - [x] Incomplete

## Notes
- Do not sort (reorganize the order the checks appear), just filter which ones are shown.

**Comment by Thajny** [comment]
![image 2017-05-24 at 6 14 14 pm](https://cloud.githubusercontent.com/assets/21183377/26429749/677e8cb0-40ae-11e7-8b1b-8c28ce71f914.png)

**Comment by Thajny** [comment]
![menu_redesign](https://cloud.githubusercontent.com/assets/21183377/26648492/429973f6-4608-11e7-9dee-be71e5131129.png)
