### ISSUE TITLE
Design Navigation: To Language (Due 10/5)

### ISSUE THREAD

**Issue by benjore** [unfoldingWord-dev/design#2]
Web Team: #25 https://github.com/unfoldingWord-dev/door43.org/issues/25

**Comment by Thajny** [comment]
![language picker](https://cloud.githubusercontent.com/assets/21183377/19097969/ec268ae0-8a6e-11e6-9f48-ca7839a21b37.jpg)
![language picker_region search](https://cloud.githubusercontent.com/assets/21183377/19097970/ec2fd280-8a6e-11e6-8117-2e0dffc3369b.jpg)
![language picker_region](https://cloud.githubusercontent.com/assets/21183377/19097971/ec310da8-8a6e-11e6-9d8d-105bfbabaa16.jpg)
![language picker_search](https://cloud.githubusercontent.com/assets/21183377/19097972/ec3ba2cc-8a6e-11e6-854a-6e4556f1c088.jpg)
