### ISSUE TITLE
Design Releases Feature for Project Pages

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/design#22]
We need a design that implements what a Release should look like, see https://github.com/unfoldingWord-dev/door43.org/issues/33.

**Comment by Thajny** [comment]
![issue 22](https://cloud.githubusercontent.com/assets/21183377/19782863/53697d5a-9c55-11e6-9b8a-2bace243972c.jpg)

**Comment by Thajny** [comment]
![issue 22](https://cloud.githubusercontent.com/assets/21183377/19784171/5dc08d70-9c5a-11e6-8f48-95234c4cfdf3.jpg)
