### ISSUE TITLE
Design new tW check page layout

### ISSUE THREAD

**Issue by benjore** [unfoldingWord-dev/design#32]
![2016-10-12 14 13 38](https://cloud.githubusercontent.com/assets/13352518/19323118/a69d1298-9089-11e6-8b1d-80a6708a669f.jpg)

**Comment by Thajny** [comment]
![tw_mockup 1](https://cloud.githubusercontent.com/assets/21183377/19448691/8854e666-9468-11e6-8c0b-cda7d521a59b.jpg)
![tw_mockup 2](https://cloud.githubusercontent.com/assets/21183377/19448692/88590458-9468-11e6-8aea-96ca1099652c.jpg)

**Comment by Thajny** [comment]
![asset 3](https://cloud.githubusercontent.com/assets/21183377/19606641/592742de-9789-11e6-8867-bb58baf59d70.jpg)
![asset 4](https://cloud.githubusercontent.com/assets/21183377/19606643/592c42ca-9789-11e6-962f-0839979516dc.jpg)
![asset 5](https://cloud.githubusercontent.com/assets/21183377/19606640/5926e1ae-9789-11e6-80fe-c84d48d353c7.jpg)
![asset 6](https://cloud.githubusercontent.com/assets/21183377/19606642/592aabea-9789-11e6-9341-1f5d1021c0aa.jpg)
![tw mockup 1](https://cloud.githubusercontent.com/assets/21183377/19606644/592da020-9789-11e6-9afe-f1fa89113e68.jpg)
![tw mockup 2](https://cloud.githubusercontent.com/assets/21183377/19606645/592e65d2-9789-11e6-8e51-6823d4cb10db.jpg)
![tw mockup 3](https://cloud.githubusercontent.com/assets/21183377/19606646/59352642-9789-11e6-9ec3-925ee0d6a7c6.jpg)
