### ISSUE TITLE
Design new tN page

### ISSUE THREAD

**Issue by benjore** [unfoldingWord-dev/design#33]
![2016-10-12 14 32 01](https://cloud.githubusercontent.com/assets/13352518/19323217/f370a65c-9089-11e6-9f84-e3f9865807fa.jpg)

**Comment by Thajny** [comment]
![tn_mockup 1](https://cloud.githubusercontent.com/assets/21183377/19448707/979309a0-9468-11e6-8a2d-3ba0ae8ca385.jpg)

**Comment by Thajny** [comment]
![tn mockup](https://cloud.githubusercontent.com/assets/21183377/19606757/63059692-978a-11e6-8081-5906b4c2bc9c.jpg)
