### ISSUE TITLE
Checking Tool tweaks

### ISSUE THREAD

**Issue by benjore** [unfoldingWord-dev/design#35]
- [ ] Jesse - have the icon (e.g. tN, tW) show up in the menu
- [x] Klappy - a list of projects (not necessarily books of the Bible)
- [x] Klappy - how to prompt text highlighting
- [x] Tim - move slider down to lower (right), then in upper right say “highlight target phrase/word”. As you highlight, it adds it into a text box. Need to be able to not highlight, but want to prompt them 
- [ ] Tim - Save & Continue button. On the bottom right. (A column of buttons along the right side of the blue box giving navigation.)
- [x] Jesse - change the + for see Scriptural context -> ^ .

**Comment by klappy** [comment]
Current listing of projects: ![screen shot 2016-10-24 at 3 32 45 pm](https://cloud.githubusercontent.com/assets/118073/19660780/2f3e9332-99ff-11e6-8da5-937e3cfb4114.png)

Should show:  Language, Book, ULB
