### ISSUE TITLE
Research Screenshot/Storyboard Sync Options

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/design#37]
## Story

As a *PO*|*stakeholder* I want to see screen/storyboard changes right away so that I can review them for modifications.

I also want it to be easier for Thomas!

Time boxed at 2.56 hours.

**Comment by Thajny** [comment]
https://docs.google.com/document/d/1RyzuzmpMC7S6jzop2wiYa2imV-qWYxalsOVj5WXG_mg/edit?usp=sharing

**Comment by Thajny** [comment]
Those are some of my findings. I think InVision will be the way to go for this. I also looked into sketch a bit - It doesn't feel as intuitive to me, but I think for just storyboarding it will work out a bit better, especially with InVision.

**Comment by jag3773** [comment]
InVision is the winner!
