### ISSUE TITLE
tC: Create Outline of Workflow

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/design#39]
## Story

As a *PO*|*designer*|*developer* I want an outline of the various steps in the tC workflow so that I know how to model/build the app.

## Notes

Should be a Google Doc that others can collaborate and comment on.

**Comment by Thajny** [comment]
https://docs.google.com/document/d/1c9Gum6mRogfDD7obXHAFu07xSp2vdBO6mFpfCBXoSWs/edit?usp=sharing
