### ISSUE TITLE
tC: Revise Storyboard

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/design#42]
Incorporate feedback from devs and PO and outline workflow.

**Comment by benjore** [comment]
Notes

 from Sprint Review: 
- [x] Jesse - hover over words to get more info
- [x] Christine - Same resources in the top across all projects? 
- [x] Christine - change ARD -> tHelps
- [x] Jesse - make the tHelps a pop-out not a modal. [Klappy & Tim - leave it modal for now, maybe make pop-out a stretch goal]
- [x] Tim - The arrow moves the highlight, not the wheel (down advances/next, up moves backwards/previous)
- [x] Jesse - add scroll bar to far left list (tW list)
- [x] Tim - when scrolling in the submenu, keep your place and don’t change your place until you click on the word, or snap back to “home” position if click elsewhere on the screen. 
- [x] Iteration 1 = scroll the selected as a “free float” and scroll off the screen as needed. 
- [x] Iteration 2 = somehow indicate where the “active” check is (some indication at the top/bottom?) 
- [x] Thomas - Add "correct in context" screen.
