### ISSUE TITLE
Design Menu and Settings UX/UI

### ISSUE THREAD

**Issue by klappy** [unfoldingWord-dev/design#45]
As a stakeholder, I want the Menus and Settings UX to be planned so that I know what it will look like.

**Comment by benjore** [comment]
My Projects Menu
 * [ ] On the left - local projects, 
 * [ ] on the right - online projects, 
 * [ ] in the middle - sync icon / upload icon / download icon. 
 * [ ] On the bottom left - Import a New local project [button], 
 * [ ] on the bottom right - load a new project [button - from someone else’s repo]
 * [ ] Project info -> tool tip
