### ISSUE TITLE
Menu/Settings: Incorporate Sprint Review Notes

### ISSUE THREAD

**Issue by klappy** [unfoldingWord-dev/design#51]

**Comment by benjore** [comment]
- Application tab 
  - [ ]  Tim - Disabled -> Offline/Online
  - [ ]  Tim - allow the user to go back (register new account tab) - breadcrumbs, back button, etc. 
  - [ ]  Jesse - also need to have a warning that username & email address will be available online. [Wording is available]
  - [ ]  Christine - add which version of tC 
  - [ ]  Tim - add feedback loop 
- Projects Menu
  - [ ]  Tim - remove the progress circle from the menu [link it to tM]
  - [ ]  Jesse - Archive button
  - [ ]  Klappy - Default = Browse Door43 Projects. Enter Web Address = not default. Tim - Retrieve from tM will need to be available. Klappy - add a link to log in. 
  - [ ]  Tim - make My Projects sortable
  - [ ]  Klappy - add project name, language code, Christine - filter to most recent at the top. 
  - [ ]  Tim - hide Archive behind three-dot menu. Jesse - remove archive completely as sorting will take care of it. 
  - [ ]  Jesse - Sync -> Upload or change icon. 
- Tools Menu
  - [ ]  Tim - What are we going to name these checks? We need to call the checks what they are. 
  - [ ]  Jesse - add who created the check (by unfoldingWord)
  - [ ]  Tim - make our checks default. 
  - [ ]  Jesse - 2 different things going - available tools and select tool.
