### ISSUE TITLE
Design Tag Display Pages

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/design#55]
We are adding support for a tagging system in Gogs ( https://github.com/unfoldingWord-dev/gogs/issues/51 ) and need some designs for a couple of pages.

1. A design for the page that lists all the tags (e.g. http://test.door43.org:3000/Door43/en-ubn/hashtags)
2. A design for the page that lists everywhere that a single page shows up ( http://test.door43.org:3000/Door43/en-ubn/hashtags/da-belbapt ).  This page also needs a second box that shows links to the glossary or article pages.

**Comment by lrsallee** [comment]
I don't see why the pages need to be much fancier than those samples are. Looks like they would work.

I am hoping that we will also be able to have pages to list all tags with a single prefix. For example, an Article page. Even better would be to have page with a table to show both the accepted Article list and the proposed article list.
