### ISSUE TITLE
Follow up to #55 (Hashtags)

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/design#64]
* [x] Add clear button on main list page to zero out the letters highlighted
* [x] Make “back” link in to a breadcrumb = < Hashtag list   < A -- and put it on the left above the page title

**Comment by benjore** [comment]
Add clear and highlight all buttons.
Make “back” link in to a breadcrumb = < Hashtag list   < A
Add the number of # hits in each file
