### ISSUE TITLE
new live.door43

### ISSUE THREAD

**Issue by ChrisJarka** [unfoldingWord-dev/design#68]
It is so nice to have the 'See this on Door43' in the Gogs repo - now....
Would it be possible to have a link back to the Gogs repo on the live.door43 page?
That way the end-user can quickly access the page if they started at the live.door43 page.

I'm thinking of something like the 'edit on github' link that is on the info.readthedocs.io pages.

**Comment by Thajny** [comment]
![obs](https://cloud.githubusercontent.com/assets/21183377/26130358/f6d60cc2-3a59-11e7-8e98-ac671b054fa7.png)

**Comment by jag3773** [comment]
@Thajny let’s use "See on DCS", and it needs to be in the sidebar.

**Comment by Thajny** [comment]
![obs](https://cloud.githubusercontent.com/assets/21183377/26648598/9a3ec6ec-4608-11e7-906e-a28b4c53624f.png)

**Comment by Thajny** [comment]
![obs](https://cloud.githubusercontent.com/assets/21183377/26648645/c57c6fa8-4608-11e7-996f-3e9d5687c071.png)

**Comment by jag3773** [comment]
Issue moved to [unfoldingWord-dev/door43.org #559](https://github.com/unfoldingWord-dev/door43.org/issues/559) via [**ZenHub**](https://www.zenhub.com/)
