### ISSUE TITLE
InVision Beta workflow with consistent mockups

### ISSUE THREAD

**Issue by klappy** [unfoldingWord-dev/design#71]
There have been a lot of UI/UX changes the past few months.
We need a single InVision mockup, that includes each screen with consistent UI elements.

**Comment by Thajny** [comment]
----------1st Draft Screen Checklist----------

- [ ] Blank Slate Screen
- [ ] Load Project Screen Modal
- [ ] Import Local/Online
- [ ] Load Tool Screen Modal
- [ ] Default tC UI Screen (Luke 1:35 Angel)
- [ ] Default Menu modal (sign in screen)
- [ ] New User Creation
- [ ] Fill out text fields
- [ ] Default Account page
- [ ] Feedback dropdown
- [ ] TACT Options
- [ ] Global Settings
- [ ] Settings Dropdowns
- [ ] Global Setting edit
- [ ] Add Scripture Resource
- [ ] Remove Resource
- [ ] Instructions Tab (Default UI)
- [ ] Notes Tab (Default UI)
- [ ] Correct/Flagged Active/inactive button overlays
- [ ] Next Check (2-3)
- [ ] Change to translationNotes Tool
- [ ] translationNotes default UI
- [ ] Sign out
