### ISSUE TITLE
Update tC Mockup/Workflow

### ISSUE THREAD

**Issue by klappy** [unfoldingWord-dev/design#75]
Ben can you replace this with your notes?

**Comment by benjore** [comment]
- Jesse
 - [x] Change Glossary to Index
- Klappy
  - [x]  drop the Bible references in the tH modal pop-up
- Klappy
  - tN
    - [x]  in black tN card below, drop “Exclusive We”
    - [x]  make the quote “among us” bold (same formatting as the current “Exclusive We”
    - [x]  drop the link at the bottom. 
    - [x]  Change “translationNotes” -> “Select the target translation for:”
  - tN - tHelps
    - [x]  Drop first paragraph
    - [x]  Make title bold “Exclusive We” 
    - [x]  Bold subtitles (H3 - same as HTML) (see https://git.door43.org/Door43/en-ta-translate-vol2/src/master/content/figs_exclusive.md#description )
  - tW
    - [x]  The devs have a cleaner tHelps (gray right-hand pane). (See https://git.door43.org/Door43/en-tw/src/master/content/other/12tribesofisrael.md#twelve-tribes-of-israel )
    - [x]  If “Flag” is selected, automatically bring “suggest change” to the front (when you navigate to the next check, it brings up the tW again) 
    - [x]  Have the highlighted word show up in the menu for that check - e.g. for an undone check it would include the book name too (Luke 11:51), once the check is done, the book name would drop and the highlighted text would appear after the check (11:51 [check] Abel)
    - [x]  Put check/flag/[gutter] on the left side of the submenu. 
Change “translationWords” (in the black card at the bottom) -> “Select the target translation for:”
    - [x]  Highlight the tW/tN in the ULB at the top.
