### ISSUE TITLE
Blue boundary for the bottom of the checking pane

### ISSUE THREAD

**Issue by benjore** [unfoldingWord-dev/design#78]
See https://github.com/unfoldingWord-dev/translationCore/issues/590 . 

# Definition of Done
- [x] Mockup for tW tab (not needing scrolling)
- [x] Mockup for Instructions tab, scrolled to the top
- [x] Mockup for Instructions tab, scrolled to the bottom

**Comment by benjore** [comment]
Blue boundary will be stagnate. The content inside the gray "cards" can scroll.

**Comment by Thajny** [comment]
https://xd.adobe.com/view/4fad7c37-5cbd-48ea-86cd-493b212ddaac/screen/4a4b84ab-7c6b-4e3c-ac16-9ba7ba03d76f/tranlsationWords-Instructions-4
