### ISSUE TITLE
Scripture Pane Modal Pop-up Modifications

### ISSUE THREAD

**Issue by benjore** [unfoldingWord-dev/design#82]
- [x] 1. Read
  - [x] Add "chapter:verse" to all references in Scripture Pane
  - [x] Only have the icon (Move words "View Context" into a tool tip)
- [x] 2. Select
  - [x] Create "expand" icon for the translation pane
- [x] Modal Pop-up 
  - [x] Add "chapter:verse" to all references in the Modal pop-up
  - [x] Keep the chapter ("Chapter 22") In-line but not in the header
  - [x] Keep what’s on the Scripture Pane (Title) in the Modal Popout (e.g. English (ULB), Greek (UGNT))

**Comment by Thajny** [comment]
![scripture pane modal add 2 bibles](https://cloud.githubusercontent.com/assets/21183377/23438700/aa517322-fdd8-11e6-91fe-f3f77daef751.png)
![scripture pane modal chapter heading](https://cloud.githubusercontent.com/assets/21183377/23438699/aa508b38-fdd8-11e6-85ff-9f53b6062f96.png)
![scripture pane modal](https://cloud.githubusercontent.com/assets/21183377/23438698/aa50b784-fdd8-11e6-87aa-329ac54399aa.png)
